language: ruby
rvm: '2.6.0'
script:
  - bundle exec jekyll build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  github-url: https://github.com/Answart/answart.github.io
  fqdn: https://alexandraswart.com
  repo: answart.github.io
branches:
  only:
  - gh-pages